steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to instance
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      mkdir -p ~/root/.ssh && \
      gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/root/.ssh/id_rsa && \
      chmod 600 ~/root/.ssh/id_rsa && \
      gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > ~/root/.ssh/id_rsa.pub && \
      chmod 600 ~/root/.ssh/id_rsa.pub && \
      set -x && \
      ssh -i ~/root/.ssh/id_rsa system@34.139.250.184 "cd ~/Documents/backend-system/ && npm run start-production"

      